#!/bin/bash

END=$1

for i in $(seq 1 $END);
do
    docker run -it -d arcolife/docker_comp    
done
echo "$END containers have been deployed.."

# docker ps > containers_details
# cd scripts/
# python read_container_details.py
# cd ..

export CURRENT_WORKERS=$(docker ps -q | head -n $END)

docker inspect $CURRENT_WORKERS > container_info.json
# docker inspect $(docker ps  | grep arcolife/docker_comp | awk -F' ' '{print $1}') > container_info.json

echo "updating worker details on server.."
curl -H "Content-type: application/json" -X POST http://$DC_HOST:$DC_PORT/get_details/ -d @container_info.json